ALTER TABLE WAREHOUSE ADD TOLL_FREE_NUMBER VARCHAR2(20);
ALTER TABLE AT_WAREHOUSE ADD TOLL_FREE_NUMBER VARCHAR2(20);

  
-----------------------------------------------------------------------------------------------------------------------------------------------------------


ALTER TABLE CIMM_USERS ADD (ACCOUNT_MANAGER VARCHAR2(50), CLOSEST_BRANCH VARCHAR2(50) );
ALTER TABLE CIMM_USERS ADD (PROFILE_IMAGE VARCHAR2(150));

ALTER table Cimm_users MODIFY ADDRESS1 varchar2(100);
ALTER table Cimm_users MODIFY ADDRESS2 varchar2(100);

ALTER TABLE AT_CIMM_USERS ADD (PROFILE_IMAGE VARCHAR2(150));
ALTER TABLE AT_CIMM_USERS ADD ( ACCOUNT_MANAGER VARCHAR2(50), CLOSEST_BRANCH VARCHAR2(50) );


ALTER TABLE BUYING_COMPANY ADD TEMP_GUID VARCHAR(100);
ALTER TABLE BUYING_COMPANY ADD SHIP_TO_ID VARCHAR(255);

ALTER TABLE AT_BUYING_COMPANY ADD TEMP_GUID VARCHAR(100);
ALTER TABLE AT_BUYING_COMPANY ADD SHIP_TO_ID VARCHAR(255);

ALTER TABLE BC_ADDRESS_BOOK ADD SHIP_TO_NAME VARCHAR(255);

ALTER TABLE AT_BC_ADDRESS_BOOK ADD SHIP_TO_NAME VARCHAR(255);
  
-----------------------------------------------------------------------------------------------------------------------------------------------------------

  
ALTER TABLE CUSTOMER_PART_NUMBERS ADD ( SHIP_TO_ID VARCHAR2(50), RECORD_TYPE VARCHAR2(10), RECORD_DESCRIPTION VARCHAR2(20));
ALTER TABLE AT_CUSTOMER_PART_NUMBERS ADD ( SHIP_TO_ID VARCHAR2(50), RECORD_TYPE VARCHAR2(10), RECORD_DESCRIPTION VARCHAR2(20));

  
-----------------------------------------------------------------------------------------------------------------------------------------------------------

  
ALTER TABLE SHIP_VIA_DELIVERY_TYPE ADD SITE_ID number;
ALTER TABLE SHIP_VIA_METHODS ADD SITE_ID number;
ALTER TABLE SHIP_VIA_VALUES ADD SITE_ID number;
ALTER TABLE ship_via ADD SHIPPING_CODE VARCHAR2(20);

  
-----------------------------------------------------------------------------------------------------------------------------------------------------------

  
ALTER TABLE SAVED_LIST_ITEMS ADD ITEMLEVEL_REQUIREDBYDATE VARCHAR2(30);
ALTER TABLE SAVED_LIST_ITEMS ADD BRAND VARCHAR2(200 BYTE);
ALTER TABLE SAVED_LIST_ITEMS ADD PART_NUMBER VARCHAR2(200 BYTE);
ALTER TABLE SAVED_LIST_ITEMS ADD PRICE VARCHAR2(200 BYTE);
ALTER TABLE SAVED_LIST_ITEMS ADD MANUFACTURER VARCHAR2(200 BYTE);
ALTER TABLE SAVED_LIST_ITEMS ADD SHORT_DESCRIPTION VARCHAR2(200 byte);
ALTER TABLE SAVED_LIST_ITEMS ADD GET_PRICE_FROM VARCHAR2(200 BYTE);
ALTER TABLE SAVED_LIST_ITEMS ADD CATALOG_ID VARCHAR2(30);
ALTER TABLE SAVED_LIST_ITEMS ADD UOM VARCHAR2(100 byte);
ALTER TABLE SAVED_LIST_ITEMS ADD LINE_ITEM_COMMENT VARCHAR2(200);
ALTER TABLE SAVED_LIST_ITEMS ADD ITEM_LEVEL_SHIPVIA VARCHAR2(30);
ALTER TABLE SAVED_LIST_ITEMS ADD ITEM_LEVEL_SHIPVIA_DESC VARCHAR2(30);

ALTER TABLE AT_SAVED_LIST_ITEMS ADD ITEM_LEVEL_SHIPVIA VARCHAR2(30);
ALTER TABLE AT_SAVED_LIST_ITEMS ADD ITEM_LEVEL_SHIPVIA_DESC VARCHAR2(30);
ALTER TABLE AT_SAVED_LIST_ITEMS ADD LINE_ITEM_COMMENT VARCHAR2(200);
ALTER TABLE AT_SAVED_LIST_ITEMS ADD UOM VARCHAR2(100 byte);
ALTER TABLE AT_SAVED_LIST_ITEMS ADD CATALOG_ID VARCHAR2(30); 
ALTER TABLE AT_SAVED_LIST_ITEMS ADD ITEMLEVEL_REQUIREDBYDATE VARCHAR2(30);
ALTER TABLE AT_SAVED_LIST_ITEMS ADD BRAND VARCHAR2(200 BYTE);
ALTER TABLE AT_SAVED_LIST_ITEMS ADD PART_NUMBER VARCHAR2(200 BYTE);
ALTER TABLE AT_SAVED_LIST_ITEMS ADD PRICE VARCHAR2(200 BYTE);
ALTER TABLE AT_SAVED_LIST_ITEMS ADD MANUFACTURER VARCHAR2(200 BYTE);
ALTER TABLE AT_SAVED_LIST_ITEMS ADD SHORT_DESCRIPTION VARCHAR2(200 byte);
ALTER TABLE AT_SAVED_LIST_ITEMS ADD GET_PRICE_FROM VARCHAR2(200 BYTE);

  
-----------------------------------------------------------------------------------------------------------------------------------------------------------

  
ALTER TABLE ship_via ADD SITE_ID number;

  
-----------------------------------------------------------------------------------------------------------------------------------------------------------

  
ALTER TABLE CART ADD CATALOG_ID VARCHAR2(30);
ALTER TABLE CART ADD BRAND VARCHAR2(200 BYTE);
ALTER TABLE CART ADD PART_NUMBER VARCHAR2(200 BYTE);
ALTER TABLE CART ADD PRICE VARCHAR2(200 BYTE);
ALTER TABLE CART ADD MANUFACTURER VARCHAR2(200 BYTE);
ALTER TABLE cart ADD SHORT_DESCRIPTION VARCHAR2(200 byte);
ALTER TABLE CART ADD GET_PRICE_FROM VARCHAR2(200 BYTE);
ALTER TABLE CART ADD UOM VARCHAR2(100 byte);
ALTER TABLE CART ADD ITEM_TYPE VARCHAR2(100 byte);
ALTER TABLE CART ADD MIN_ORDER_QTY NUMBER;
ALTER TABLE CART ADD ITEM_WEIGHT decimal(16,5);
ALTER TABLE CART ADD UNITS decimal(16,5);
ALTER TABLE CART ADD ITEMLEVEL_REQUIREDBYDATE VARCHAR2(30);
ALTER TABLE CART ADD ITEM_LEVEL_SHIPVIA VARCHAR2(30);
ALTER TABLE CART ADD ITEM_LEVEL_SHIPVIA_DESC VARCHAR2(30);
ALTER TABLE CART ADD UOM VARCHAR2(100 byte);  


-----------------------------------------------------------------------------------------------------------------------------------------------------------

  
ALTER TABLE QUOTE_CART ADD BRAND VARCHAR2(200 BYTE);
ALTER TABLE QUOTE_CART ADD PART_NUMBER VARCHAR2(200 BYTE);
ALTER TABLE QUOTE_CART ADD PRICE VARCHAR2(200 BYTE);
ALTER TABLE QUOTE_CART ADD MANUFACTURER VARCHAR2(200 BYTE);
ALTER TABLE QUOTE_CART ADD SHORT_DESCRIPTION VARCHAR2(200 BYTE);
ALTER TABLE QUOTE_CART ADD GET_PRICE_FROM VARCHAR2(200 BYTE);
ALTER TABLE QUOTE_CART ADD CATALOG_ID VARCHAR2(30);
ALTER TABLE QUOTE_CART ADD ITEMLEVEL_REQUIREDBYDATE VARCHAR2(30);
ALTER TABLE QUOTE_CART ADD ITEM_LEVEL_SHIPVIA VARCHAR2(30);
ALTER TABLE QUOTE_CART ADD ITEM_LEVEL_SHIPVIA_DESC VARCHAR2(30);

ALTER TABLE AT_QUOTE_CART ADD CATALOG_ID VARCHAR2(30);
ALTER TABLE AT_QUOTE_CART ADD BRAND VARCHAR2(200 BYTE);
ALTER TABLE AT_QUOTE_CART ADD PART_NUMBER VARCHAR2(200 BYTE);
ALTER TABLE AT_QUOTE_CART ADD PRICE VARCHAR2(200 BYTE);
ALTER TABLE AT_QUOTE_CART ADD MANUFACTURER VARCHAR2(200 BYTE);
ALTER TABLE AT_QUOTE_CART ADD SHORT_DESCRIPTION VARCHAR2(200 BYTE);
ALTER TABLE AT_QUOTE_CART ADD GET_PRICE_FROM VARCHAR2(200 BYTE);

  
-----------------------------------------------------------------------------------------------------------------------------------------------------------

  
ALTER TABLE ORDERS ADD WAREHOUSE_CODE VARCHAR2(20);
ALTER TABLE ORDERS ADD DISCOUNT_TYPE VARCHAR2(200 BYTE);
ALTER TABLE ORDERS ADD DISCOUNT_COUPON_CODE VARCHAR2(200 BYTE);
ALTER TABLE ORDERS ADD DISCOUNT_PERCENTAGE number;
ALTER TABLE ORDERS ADD DISCOUNT_AMOUNT number;
ALTER TABLE ORDERS MODIFY SHIP_METHOD_ID VARCHAR2(50);
ALTER TABLE ORDERS ADD ORDER_ERP_ID VARCHAR2(100);
ALTER TABLE ORDERS ADD ORDER_SUFFIX VARCHAR2(10);
ALTER TABLE Orders ADD ERP_ORDER_MESSAGE VARCHAR2(500);
ALTER TABLE Orders ADD PAYPAL_TOKEN VARCHAR2(200);
ALTER TABLE Orders ADD PAYPAL_PAYER_ID VARCHAR2(200);
ALTER TABLE ORDERS ADD BILL_COMPANY_NAME VARCHAR2(200);
ALTER TABLE ORDERS ADD SHIP_COMPANY_NAME VARCHAR2(200);
ALTER TABLE ORDERS ADD DELIVERY_FEE VARCHAR2(200);
alter table orders add (GAS_PO_NUMBER varchar2(200));
alter table orders add (CC_CVV_RESULT_CODE varchar2(200));
alter table orders add (CC_AVS_RESULT_CODE varchar2(200));
ALTER TABLE ORDERS ADD SHIPPING_ATTENTION VARCHAR2(20);

ALTER TABLE AT_ORDERS ADD SHIPPING_ATTENTION VARCHAR2(20);
alter table at_orders add (CC_CVV_RESULT_CODE varchar2(200));
alter table at_orders add (CC_AVS_RESULT_CODE varchar2(200));
alter table at_orders add (GAS_PO_NUMBER varchar2(200));
ALTER TABLE AT_ORDERS ADD DELIVERY_FEE VARCHAR2(200);
ALTER TABLE AT_ORDERS ADD BILL_COMPANY_NAME VARCHAR2(200);
ALTER TABLE AT_ORDERS ADD SHIP_COMPANY_NAME VARCHAR2(200);
ALTER TABLE AT_Orders ADD PAYPAL_PAYER_ID VARCHAR2(200);
ALTER TABLE AT_Orders ADD PAYPAL_TOKEN VARCHAR2(200);
ALTER TABLE AT_Orders ADD ERP_ORDER_MESSAGE VARCHAR2(500);
ALTER TABLE AT_ORDERS ADD ORDER_SUFFIX VARCHAR2(10);
ALTER TABLE AT_ORDERS ADD ORDER_ERP_ID VARCHAR2(100);
ALTER TABLE AT_ORDERS MODIFY SHIP_METHOD_ID VARCHAR2(50);
ALTER TABLE AT_ORDERS ADD DISCOUNT_TYPE VARCHAR2(200 BYTE);
ALTER TABLE AT_ORDERS ADD DISCOUNT_COUPON_CODE VARCHAR2(200 BYTE);
ALTER TABLE AT_ORDERS ADD DISCOUNT_PERCENTAGE number;
ALTER TABLE AT_ORDERS ADD DISCOUNT_AMOUNT number;

ALTER TABLE ORDER_ITEMS ADD HAZARDIOUS_MATERIAL VARCHAR2(1);
ALTER TABLE order_items ADD DISCOUNT_TYPE VARCHAR2(200 BYTE);
ALTER TABLE order_items ADD DISCOUNT_COUPON_CODE VARCHAR2(200 BYTE);
ALTER TABLE order_items ADD DISCOUNT_PERCENTAGE number;
ALTER TABLE order_items ADD DISCOUNT_AMOUNT number;
ALTER TABLE ORDER_ITEMS ADD CATALOG_ID VARCHAR2(30);
ALTER TABLE order_items ADD UNITS_PER_STOCKING_STRING VARCHAR2(10 BYTE);
ALTER TABLE order_items ADD UNITS_PER_STOCKING number;
ALTER TABLE ORDER_ITEMS ADD CART_ID number;
ALTER TABLE order_items ADD LEAD_TIME VARCHAR2(100);
alter table order_items add (MANUFACTURER varchar2(100));
ALTER TABLE  ORDER_ITEMS ADD LIST_PRICE NUMBER;
ALTER TABLE  ORDER_ITEMS ADD CALL_FOR_PRICE VARCHAR2(1) ;
ALTER TABLE ORDER_ITEMS ADD ITEMLEVEL_REQUIREDBYDATE VARCHAR2(30);

ALTER TABLE AT_ORDER_ITEMS ADD ITEMLEVEL_REQUIREDBYDATE VARCHAR2(30);
ALTER TABLE  AT_ORDER_ITEMS ADD CALL_FOR_PRICE VARCHAR2(1) ;
ALTER TABLE  AT_ORDER_ITEMS ADD LIST_PRICE NUMBER ;
alter table at_order_items add (MANUFACTURER varchar2(100));
ALTER TABLE AT_ORDER_ITEMS ADD LEAD_TIME VARCHAR2(100);
ALTER TABLE at_ORDER_ITEMS ADD CART_ID number;
ALTER TABLE at_order_items ADD UNITS_PER_STOCKING_STRING VARCHAR2(10 BYTE);
ALTER TABLE at_order_items ADD UNITS_PER_STOCKING number;

  
-----------------------------------------------------------------------------------------------------------------------------------------------------------

  
ALTER TABLE STATIC_PAGES ADD (PAGE_TYPE VARCHAR2(10),HEADER VARCHAR2(50),FOOTER VARCHAR2(50),HOME_PAGE_ICON VARCHAR2(1));
ALTER TABLE AT_STATIC_PAGES ADD (PAGE_TYPE VARCHAR2(10), HEADER VARCHAR2(50), FOOTER VARCHAR2(50), HOME_PAGE_ICON VARCHAR2(1));

  
-----------------------------------------------------------------------------------------------------------------------------------------------------------
desc CIMM_USERS;
create table CIMM_USERS_BAK as select * from CIMM_USERS;
alter table CIMM_USERS add (ECLIPSE_CONTACT_ID_CHAR varchar2(100));
update CIMM_USERS set ECLIPSE_CONTACT_ID_CHAR=ECLIPSE_CONTACT_ID;
alter table CIMM_USERS rename column ECLIPSE_CONTACT_ID to ECLIPSE_CONTACT_ID_number;
alter table CIMM_USERS rename column ECLIPSE_CONTACT_ID_CHAR to ECLIPSE_CONTACT_ID;
alter table CIMM_USERS drop column ECLIPSE_CONTACT_ID_NUMBER;
desc CIMM_USERS;
select * from CIMM_USERS;
-----
desc AT_CIMM_USERS;
create table AT_CIMM_USERS_BAK as select * from AT_CIMM_USERS;
alter table AT_CIMM_USERS add (ECLIPSE_CONTACT_ID_CHAR varchar2(100));
update AT_CIMM_USERS set ECLIPSE_CONTACT_ID_CHAR=ECLIPSE_CONTACT_ID;
alter table AT_CIMM_USERS rename column ECLIPSE_CONTACT_ID to ECLIPSE_CONTACT_ID_number;
alter table AT_CIMM_USERS rename column ECLIPSE_CONTACT_ID_CHAR to ECLIPSE_CONTACT_ID;
alter table AT_CIMM_USERS drop column ECLIPSE_CONTACT_ID_NUMBER;
desc AT_CIMM_USERS;
----
desc BC_ADDRESS_BOOK
create table BC_ADDRESS_BOOK_BAK as select * from BC_ADDRESS_BOOK;
alter table BC_ADDRESS_BOOK add (ENTITY_ID_CHAR varchar2(100));
update BC_ADDRESS_BOOK set ENTITY_ID_CHAR=ENTITY_ID;
alter table BC_ADDRESS_BOOK rename column ENTITY_ID to ENTITY_ID_number;
alter table BC_ADDRESS_BOOK rename column ENTITY_ID_CHAR to ENTITY_ID;
alter table BC_ADDRESS_BOOK drop column ENTITY_ID_NUMBER;
desc BC_ADDRESS_BOOK
------
desc BUYING_COMPANY;
create table BUYING_COMPANY_BAK as select * from BUYING_COMPANY;
alter table BUYING_COMPANY add (ENTITY_ID_CHAR varchar2(100));
update BUYING_COMPANY set ENTITY_ID_CHAR=ENTITY_ID;
alter table BUYING_COMPANY rename column ENTITY_ID to ENTITY_ID_number;
alter table BUYING_COMPANY rename column ENTITY_ID_CHAR to ENTITY_ID;
alter table BUYING_COMPANY drop column ENTITY_ID_NUMBER;
desc BUYING_COMPANY;
----------
desc AT_BC_ADDRESS_BOOK;
create table AT_BC_ADDRESS_BOOK_BAK as select * from AT_BC_ADDRESS_BOOK;
alter table AT_BC_ADDRESS_BOOK add (ENTITY_ID_CHAR varchar2(100));
update AT_BC_ADDRESS_BOOK set ENTITY_ID_CHAR=ENTITY_ID;
alter table AT_BC_ADDRESS_BOOK rename column ENTITY_ID to ENTITY_ID_number;
alter table AT_BC_ADDRESS_BOOK rename column ENTITY_ID_CHAR to ENTITY_ID;
alter table AT_BC_ADDRESS_BOOK drop column ENTITY_ID_NUMBER;
desc AT_BC_ADDRESS_BOOK
  
-----------------------------------------------------------------------------------------------------------------------------------------------------------

alter table AT_orders add CC_TYPE  VARCHAR2(50);
alter table orders add CC_TYPE VARCHAR2(50);
alter table orders MODIFY  SHIP_COUNTRY_CODE  VARCHAR2(20);
alter table at_orders MODIFY  SHIP_COUNTRY_CODE  VARCHAR2(20);
alter table AT_orders MODIFY SHIP_METHOD_ID  VARCHAR2(50);
alter table orders MODIFY SHIP_METHOD_ID  VARCHAR2(50);  
  
-----------------------------------------------------------------------------------------------------------------------------------------------------------

desc AT_orders;
create table AT_orders_BAK as select * from AT_orders;
alter table AT_orders add (SHIP_METHOD_ID_NEW varchar2(50));
update AT_orders set SHIP_METHOD_ID_NEW=SHIP_METHOD_ID;
alter table AT_orders rename column SHIP_METHOD_ID to SHIP_METHOD_ID_NEW2;
alter table AT_orders rename column SHIP_METHOD_ID_NEW to SHIP_METHOD_ID;
alter table AT_orders drop column SHIP_METHOD_ID_NEW2;
desc AT_orders;
select * from AT_orders;

desc orders;
create table orders_BAK as select * from orders;
alter table orders add (SHIP_METHOD_ID_NEW varchar2(50));
update orders set SHIP_METHOD_ID_NEW=SHIP_METHOD_ID;
alter table orders rename column SHIP_METHOD_ID to SHIP_METHOD_ID_NEW2;
alter table orders rename column SHIP_METHOD_ID_NEW to SHIP_METHOD_ID;
alter table orders drop column SHIP_METHOD_ID_NEW2;
desc orders;
select * from orders;


  
-----------------------------------------------------------------------------------------------------------------------------------------------------------
ALTER TABLE warehouse ADD (TOLL_FREE VARCHAR2(150));
ALTER TABLE EVENT_REGISTRATION ADD (NEWS_LETTER TOLL_FREE(5));  

  
-----------------------------------------------------------------------------------------------------------------------------------------------------------

ALTER TABLE TAXONOMY_TREE ADD ( STATIC_PAGE_ID number, CANONICAL_URL VARCHAR2(50), TOP_BANNER_LIST_TYPE VARCHAR2(10) , LEFT_BANNER_LIST_TYPE VARCHAR2(10) , RIGHT_BANNER_LIST_TYPE VARCHAR2(10) , BOTTOM_BANNER_LIST_TYPE VARCHAR2(10) , MARKETING_DESCRIPTION VARCHAR2(4000));
ALTER TABLE item_master ADD ( NET_PRICE NUMBER,VOLUME NUMBER,DISPLAY_PRIORITY NUMBER, CANONICAL_URL VARCHAR2(50), STATUS VARCHAR2(1), 
SYNC_COMPLETED VARCHAR2(1), RESTRICTED VARCHAR2(1), VOLUME_UOM VARCHAR2(100) , COUNTRY VARCHAR2(30) 
, COO VARCHAR2(50) , STANDARD_APPROVALS VARCHAR2(2000) , APPLICATION VARCHAR2(2000));

ALTER TABLE WAREHOUSE ADD ( STATUS VARCHAR2(1), CNE_BATCH_ID number,BRANCH_LOCATION_ID NUMBER);
  
-----------------------------------------------------------------------------------------------------------------------------------------------------------

SELECT * FROM CIMM_USERS_BAK;
SELECT * FROM AT_CIMM_USERS_BAK;
DROP TABLE AT_CIMM_USERS_BAK;
DROP TABLE CIMM_USERS_BAK;

desc CIMM_USERS;
create table CIMM_USERS_BAK as select * from CIMM_USERS;
alter table CIMM_USERS add (EXTERNAL_SYSTEM2_USER_ID_CHAR varchar2(100));
update CIMM_USERS set EXTERNAL_SYSTEM2_USER_ID_CHAR=EXTERNAL_SYSTEM2_USER_ID;
alter table CIMM_USERS rename column EXTERNAL_SYSTEM2_USER_ID to EXTERNAL_SYSTEM2_USER_ID_number;
alter table CIMM_USERS rename column EXTERNAL_SYSTEM2_USER_ID_CHAR to EXTERNAL_SYSTEM2_USER_ID;
alter table CIMM_USERS drop column EXTERNAL_SYSTEM2_USER_ID_NUMBER;
desc CIMM_USERS;
select * from CIMM_USERS;
-----
desc AT_CIMM_USERS;
create table AT_CIMM_USERS_BAK as select * from AT_CIMM_USERS;
alter table AT_CIMM_USERS add (EXTERNAL_SYSTEM2_USER_ID_CHAR varchar2(100));
update AT_CIMM_USERS set EXTERNAL_SYSTEM2_USER_ID_CHAR=EXTERNAL_SYSTEM2_USER_ID;
alter table AT_CIMM_USERS rename column EXTERNAL_SYSTEM2_USER_ID to EXTERNAL_SYSTEM2_USER_ID_number;
alter table AT_CIMM_USERS rename column EXTERNAL_SYSTEM2_USER_ID_CHAR to EXTERNAL_SYSTEM2_USER_ID;
alter table AT_CIMM_USERS drop column EXTERNAL_SYSTEM2_USER_ID_NUMBER;
desc AT_CIMM_USERS;  

  
-----------------------------------------------------------------------------------------------------------------------------------------------------------

  

  
-----------------------------------------------------------------------------------------------------------------------------------------------------------

  

  
-----------------------------------------------------------------------------------------------------------------------------------------------------------

  

  
-----------------------------------------------------------------------------------------------------------------------------------------------------------

  

  
-----------------------------------------------------------------------------------------------------------------------------------------------------------

  

  
-----------------------------------------------------------------------------------------------------------------------------------------------------------

  

  
-----------------------------------------------------------------------------------------------------------------------------------------------------------

  
