-- Ship Via tables
 CREATE TABLE SHIP_VIA 
   (	SHIP_VIA_ID NUMBER NOT NULL ENABLE, 
	SHIP_VIA_CODE VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	SHIP_VIA_NAME VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	DISP_SEQ NUMBER
   );

CREATE TABLE SHIP_VIA_DELIVERY_TYPE 
   (	SHIP_TYPE_ID NUMBER NOT NULL ENABLE, 
	SHIP_DELIVERY_ID NUMBER NOT NULL ENABLE, 
	SHIP_DELIVERY_TYPE VARCHAR2(20 BYTE)
  );
  
  CREATE TABLE SHIP_VIA_METHODS 
   (	SHIP_VIA_METHOD_ID NUMBER NOT NULL ENABLE, 
	SHIP_DELIVERY_ID NUMBER, 
	SHIP_VIA_ID NUMBER
   );
   
   CREATE TABLE SHIP_VIA_VALUES 
   (	SHIP_VIA_VALUE_ID NUMBER NOT NULL ENABLE, 
	SHIP_VIA_CODE VARCHAR2(20 BYTE), 
	SHIP_VIA_DESCRIPTION VARCHAR2(50 BYTE), 
	SHIP_DELIVERY_ID NUMBER, 
	SHIP_METHOD VARCHAR2(10 BYTE)
  );
-- Ship Via tables
---------------------------------

CREATE TABLE "BLOCKED_MAIL_CONTENT" 
   (	"BLOCKED_EMAIL_ID" NUMBER, 
	"TO_EMAIL" VARCHAR2(4000 BYTE), 
	"CC_EMAIL" VARCHAR2(4000 BYTE), 
	"BCC_EMAIL" VARCHAR2(4000 BYTE), 
	"USER_EDITED" VARCHAR2(100 BYTE), 
	"UPDATED_DATETIME" DATE, 
	"SUBJECT" VARCHAR2(250 BYTE)
   )
   
---------------------------------
CREATE TABLE "SEND_MAIL_REQUEST" 
   (	"USER_IP_ADDRESS" VARCHAR2(4000 BYTE), 
	"REQUEST_COUNT" NUMBER, 
	"SESSION_ID" VARCHAR2(4000 BYTE), 
	"UPDATED_DATETIME" DATE, 
	"TOTAL_COUNT" NUMBER, 
	"LAST_HIT_TIME" NUMBER
   ) 